### ISSUE TITLE
HomeActivity 개발

### ISSUE THREAD

**Issue by tentasys** [tentasys/MyShinhanRoad#12]
https://ovenapp.io/view/THHGzlflYL6g7B4RZ1hOj2E9aFFEZgQS/cq615

Home Activity를 개발합니다.

**Comment by Genie-young** [comment]
진행 사항
![image](https://user-images.githubusercontent.com/44761908/63393735-75ab2680-c3f7-11e9-8f07-a36c4ae4d660.png)

**Comment by Genie-young** [comment]
추가 예정 
==> 자동 돌아가기? 구현
