### ISSUE TITLE
Server-Side Study

### ISSUE THREAD

**Issue by tentasys** [tentasys/MyShinhanRoad#4]
서버 단의 동작과 관련된 스터디를 진행합니다.
스터디 도중 습득한 지식 / 관련 링크를 자유롭게 댓글로 남겨주시기 바랍니다.

**Comment by refuse1993** [comment]
ngrok을 이용하면 포트포워딩을 하지 않고 외부접속이 가능할 것 같습니니다.

https://phoby.github.io/ngrok/

내일 제 PC의 apache 서버에서 확인해보겠습니다.
된다면 서버컴퓨터에 올려보겠습니다.
